name: Linting

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  NPM_CONFIG_FUND: '0'
  NPM_CONFIG_AUDIT: '0'
  SUPPRESS_SUPPORT: '1'
  NO_UPDATE_NOTIFIER: 'true'

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Run code style check
        uses: myrotvorets/composite-actions/node-run-script@master
        with:
          script: lint

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Run type check
        uses: myrotvorets/composite-actions/node-run-script@master
        with:
          script: typecheck
