name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name && github.event.sender.login != 'dependabot[bot]' ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@34cbc43f0b10c9dda284e663cf43c2ebaf83e956 # tag=v1.4.2
        with:
          egress-policy: audit

      - name: Run SonarScanner Analysis
        uses: myrotvorets/composite-actions/node-sonarscan@34269012d839ad805e0c5a26390e73cce6a26ccd
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
