name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name && github.event.sender.login != 'dependabot[bot]' ||
      github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504 # tag=v1.4.4
        with:
          egress-policy: audit

      - name: Run SonarScanner Analysis
        uses: myrotvorets/composite-actions/node-sonarscan@3ac77c5e4f319a8a03b32dade6e1954730a883d4
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
