name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

env:
  SONARSCANNER: 'true'

jobs:
  build:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    steps:
      - name: Run SonarCloud analysis
        uses: myrotvorets/composite-actions/node-sonarscan@c4c07ee643990a78097e4d7b1a1fe481b0f2c3f9 # master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          test-script: 'test:coverage'
